before_script:
  - "pip install -r .ci/requirements.txt"
  - "REQUIREMENTS=$(mktemp) && python setup.py requirements > ${REQUIREMENTS} && pip install -r ${REQUIREMENTS} && rm ${REQUIREMENTS}"
  - "pip install -r .ci/requirements_modules.txt"

build:2.7:
  image: "python:2.7"
  stage: "build"
  script:
    - "./tools/local_install.sh ~/bin"

pyflakes:2.7:
  image: "python:2.7"
  stage: "test"
  script:
    - "./tools/pyflakes.sh"

lint:2.7:
  image: "python:2.7"
  stage: "test"
  allow_failure: true
  script:
    - "./tools/weboob_lint.sh"

unittests:2.7:
  image: "python:2.7"
  stage: "test"
  script:
    - "./tools/run_tests.sh"

doc:2.7:
  image: "python:2.7"
  stage: "deploy"
  script:
    - "cd ./docs && make html"

build:3:
  image: "python:3"
  stage: "build"
  script:
    - "./tools/local_install.sh ~/bin"

pyflakes:3:
  image: "python:3"
  stage: "test"
  script:
    - "./tools/pyflakes.sh"

lint:3:
  image: "python:3"
  stage: "test"
  allow_failure: true
  script:
    - "./tools/weboob_lint.sh"

unittests:3:
  image: "python:3"
  stage: "test"
  script:
    - "./tools/run_tests.sh -3"

doc:3:
  image: "python:3"
  stage: "deploy"
  script:
    - "cd ./docs && make html"
